export const EXAM_BANKS = {
  mathPromote: [ // Lv.5 Job Change (Easy/Medium Math)
    { q: "試問複數單位平方 $i^2$ 的值是多少？", opts: ["1", "-1", "0", "$i$"], ans: "-1" },
    { q: "代數求解：$2x + 7 = 15$，請問 $x = $？", opts: ["3", "4", "5", "8"], ans: "4" },
    { q: "對數計算：$\\log_{10}(1000)$ 等於？", opts: ["1", "2", "3", "4"], ans: "3" },
    { q: "直角三角形兩股長度為 3 與 4，其斜邊長度為？", opts: ["4", "5", "6", "7"], ans: "5" },
    { q: "平面直角座標系中，點 $(3, 4)$ 到原點的距離為？", opts: ["3", "4", "5", "7"], ans: "5" },
    { q: "若一個圓的半徑為 $r$，其面積公式為？", opts: ["$2\\pi r$", "$\\pi r^2$", "$\\frac{4}{3}\\pi r^3$", "$\\pi r$"], ans: "$\\pi r^2$" },
    { q: "解方程 $3x - 5 = 10$，則 $x$ 等於？", opts: ["3", "5", "10", "15"], ans: "5" },
    { q: "一個長方形的長為 8，寬為 6，請問其面積是多少？", opts: ["14", "24", "28", "48"], ans: "48" },
    { q: "$\\sqrt{144}$ 的值是多少？", opts: ["10", "12", "14", "16"], ans: "12" },
    { q: "若 $a:b = 2:3$，且 $a=10$，則 $b$ 等於？", opts: ["12", "15", "20", "30"], ans: "15" },
    { q: "下列何者為質數？", opts: ["2", "4", "6", "8"], ans: "2" },
    { q: "計算：$15\\% \\times 200 = $？", opts: ["15", "20", "30", "45"], ans: "30" },
    { q: "一小時等於多少秒？", opts: ["60", "600", "3600", "7200"], ans: "3600" },
    { q: "三角形的內角和是多少度？", opts: ["90", "180", "270", "360"], ans: "180" },
    { q: "若 $5x + 3 = 2x + 12$，則 $x$ 等於？", opts: ["3", "4", "5", "6"], ans: "3" }
  ],
  mathLevel10: [ // Lv.9 -> Lv.10 (Hard Math / Calculus)
    { q: "求自然對數的導數：$\\frac{d}{dx} (\\ln x) = $？", opts: ["$\\frac{1}{x}$", "$e^x$", "$x$", "$\\frac{1}{x^2}$"], ans: "$\\frac{1}{x}$" },
    { q: "計算定積分：$\\int_0^1 3x^2 dx = $？", opts: ["0.5", "1", "2", "3"], ans: "1" },
    { q: "三角函數恆等式：$\\sin^2 \\theta + \\cos^2 \\theta = $？", opts: ["0", "1", "2", "不存在"], ans: "1" },
    { q: "求極限值：$\\lim_{x \\to \\infty} \\frac{2x^2 + x}{x^2 - 1} = $？", opts: ["0", "1", "2", "$\\infty$"], ans: "2" },
    { q: "求導數：$\\frac{d}{dx} (e^{2x}) = $？", opts: ["$e^{2x}$", "$2e^{2x}$", "$\\frac{1}{2}e^{2x}$", "$2x e^{2x-1}$"], ans: "$2e^{2x}$" },
    { q: "求 $\\sin(\\pi/2)$ 的值？", opts: ["0", "0.5", "1", "$\\infty$"], ans: "1" },
    { q: "求導數 $\\frac{d}{dx}(x^3 + 2x)$？", opts: ["$3x^2$", "$x^2 + 2$", "$3x^2 + 2$", "$6x$"], ans: "$3x^2 + 2$" },
    { q: "矩陣 $\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$ 的行列式值為？", opts: ["-2", "2", "10", "14"], ans: "-2" },
    { q: "求 $\\int_1^2 x dx$ 的值？", opts: ["1", "1.5", "2", "2.5"], ans: "1.5" },
    { q: "複數 $z = 3 + 4i$ 的模數 (magnitude) 為？", opts: ["5", "7", "12", "25"], ans: "5" },
    { q: "求 $\\cos(0)$ 的值？", opts: ["0", "0.5", "1", "-1"], ans: "1" },
    { q: "在座標平面上，$x^2 + y^2 = 9$ 表示一個什麼圖形？", opts: ["直線", "拋物線", "橢圓", "圓形"], ans: "圓形" },
    { q: "數列 $1, 4, 9, 16, \\dots$ 的第 $n$ 項通式為？", opts: ["$2n$", "$n^2$", "$2^n$", "$n+3$"], ans: "$n^2$" },
    { q: "求極限 $\\lim_{x \\to 0} \\frac{\\sin x}{x} =$？", opts: ["0", "1", "$\\infty$", "不存在"], ans: "1" },
    { q: "若向量 $\\vec{a} = (1, 2)$，$\\vec{b} = (3, 4)$，則內積 $\\vec{a} \\cdot \\vec{b} =$？", opts: ["7", "10", "11", "14"], ans: "11" }
  ],
  englishShop: [ // Dynamic Extra Shop Refresh Exam (English Practice)
    { q: "下列英文單字何者是「形容詞 (Adjective)」？", opts: ["Beauty", "Beautiful", "Beautify", "Beautifully"], ans: "Beautiful" },
    { q: "介係詞辨析：\"He is interested ____ music.\"", opts: ["in", "on", "at", "with"], ans: "in" },
    { q: "英文單字填空：\"I need to ______ my homework.\"", opts: ["make", "do", "take", "have"], ans: "do" },
    { q: "單字 \"Abundant\" 的最接近同義詞是？", opts: ["Scarce", "Rare", "Plentiful", "Hidden"], ans: "Plentiful" },
    { q: "慣用語 \"A piece of cake\" 的含意是？", opts: ["一塊蛋糕", "奢侈享受", "非常簡單的事", "麻煩的開端"], ans: "非常簡單的事" },
    { q: "英文單字 \"Generous\" (慷慨的) 其反義詞是？", opts: ["Kind", "Helpful", "Stingy", "Rich"], ans: "Stingy" },
    { q: "動詞 \"write\" 的過去分詞 (Past Participle) 為何？", opts: ["wrote", "written", "writing", "writes"], ans: "written" },
    { q: "單字 \"Incredible\" (不可思議的) 的同義詞是：", opts: ["Ordinary", "Boring", "Amazing", "Simple"], ans: "Amazing" },
    { q: "慣用語 \"Break a leg\" 在口語中的含意是？", opts: ["祝你好運！", "折斷大腿", "遭遇不幸", "快點跑開"], ans: "祝你好運！" },
    { q: "中翻英：「冒險」最對應的英文單字是？", opts: ["Advance", "Adventure", "Adversity", "Advice"], ans: "Adventure" },
    { q: "Which word is a synonym for \"Enormous\"?", opts: ["Tiny", "Huge", "Soft", "Quick"], ans: "Huge" },
    { q: "Fill in the blank: \"She ____ to the gym every morning.\"", opts: ["go", "goes", "going", "gone"], ans: "goes" },
    { q: "What is the opposite of \"Optimistic\"?", opts: ["Pessimistic", "Happy", "Excited", "Calm"], ans: "Pessimistic" },
    { q: "\"To call it a day\" means:", opts: ["Start working", "Finish working", "Go to sleep", "Eat lunch"], ans: "Finish working" },
    { q: "Which of these is a \"Noun\"?", opts: ["Quickly", "Happiness", "Bright", "Run"], ans: "Happiness" },
    { q: "\"By the way\" is used to:", opts: ["Change the topic", "End a conversation", "Say sorry", "Say thank you"], ans: "Change the topic" },
    { q: "The past tense of \"read\" (閱讀) is pronounced as?", opts: ["Reed", "Red", "Road", "Rude"], ans: "Red" },
    { q: "Which of these means \"放棄\"?", opts: ["Give up", "Give in", "Give out", "Give away"], ans: "Give up" },
    { q: "\"Look forward to\" should be followed by which form?", opts: ["V-ing", "to V", "V", "V-ed"], ans: "V-ing" },
    { q: "Which is the correct spelling?", opts: ["Receive", "Recieve", "Receve", "Reseive"], ans: "Receive" },
    { q: "Which stat represents \"攻擊力\" in RPG games?", opts: ["ATK", "DEF", "HP", "MP"], ans: "ATK" },
    { q: "What does \"HP\" stand for in game terms?", opts: ["Health Points", "High Power", "Hot Pizza", "Home Page"], ans: "Health Points" },
    { q: "Which job is most likely to use a \"Bow\" (弓)?", opts: ["Warrior", "Archer", "Mage", "Priest"], ans: "Archer" },
    { q: "\"Defense\" (防禦) is the opposite of:", opts: ["Attack", "Speed", "Magic", "Luck"], ans: "Attack" },
    { q: "Which class is known for using powerful magic?", opts: ["Mage", "Fighter", "Rogue", "Barbarian"], ans: "Mage" },
    { q: "The term \"Critical Hit\" refers to:", opts: ["普通攻擊", "暴擊", "閃避", "治療"], ans: "暴擊" },
    { q: "\"Evasion\" (閃避) in a game helps you to:", opts: ["Deal damage", "Avoid being hit", "Run faster", "Heal allies"], ans: "Avoid being hit" },
    { q: "Which word means \"戰士\"?", opts: ["Warrior", "Wizard", "Rogue", "Priest"], ans: "Warrior" },
    { q: "A \"Priest\" (牧師) is usually responsible for:", opts: ["Attacking", "Tanking", "Healing", "Stealing"], ans: "Healing" },
    { q: "What is a \"Novice\"?", opts: ["高手", "初學者/無職者", "商人", "國王"], ans: "初學者/無職者" },
    { q: "A \"Shield\" (盾牌) is primarily used for:", opts: ["Attack", "Defense", "Magic", "Speed"], ans: "Defense" },
    { q: "Which stat affects how fast you take your turn?", opts: ["ATK", "DEF", "SPD", "LUK"], ans: "SPD" }
  ],
  scienceHunt: [ // Dynamic High Level Hunt Interrupt (Science Trivia)
    { q: "下列關於「光合作用」的敘述，何者正確？", opts: ["放出大量一氧化碳", "主要利用葉綠素將二氧化碳與水轉化為糖與氧", "主要在夜間進行", "這是動物獲取熱量的唯一途徑"], ans: "主要利用葉綠素將二氧化碳與水轉化為糖與氧" },
    { q: "太陽系中，哪一顆行星因表面覆蓋大量氧化鐵而顯現紅色，被稱為「紅色星球」？", opts: ["水星", "金星", "火星", "土星"], ans: "火星" },
    { q: "在標準一大氣壓下，純水的「沸點」為攝氏幾度？", opts: ["0度", "50度", "100度", "200度"], ans: "100度" },
    { q: "人體血液中，主要負責輸送氧氣的「紅血球成分」是什麼？", opts: ["白血球", "血小板", "血紅素", "淋巴液"], ans: "血紅素" },
    { q: "牛頓第二運動定律中，力與質量、加速度的關係式為何？", opts: ["$E = mc^2$", "$F = ma$", "$V = IR$", "$P = IV$"], ans: "$F = ma$" },
    { q: "物質若不經過液態，由固體直接轉變為氣體的物理現象稱為？", opts: ["汽化", "昇華", "凝固", "熔化"], ans: "昇華" },
    { q: "下列哪一項是目前科學界公認生物體的基本結構與功能單位？", opts: ["分子", "原子", "細胞", "器官"], ans: "細胞" },
    { q: "地球的大氣層中，所佔體積比例「最高」的氣體是？", opts: ["氧氣", "二氧化碳", "氫氣", "氮氣"], ans: "氮氣" },
    { q: "「酸雨」的主要形成原因，是因為空氣中含有過多的何種污染物？", opts: ["二氧化碳", "硫氧化物與氮氧化物", "進性氣體", "水蒸氣"], ans: "硫氧化物與氮氧化物" },
    { q: "在力學計算中，一個物體在地球表面受到的重力加速度 $g$ 大約是多少？", opts: ["$9.8 \\text{ m/s}^2$", "$1.6 \\text{ m/s}^2$", "$12.5 \\text{ m/s}^2$", "$3.6 \\text{ m/s}^2$"], ans: "$9.8 \\text{ m/s}^2$" },
    { q: "人體中最長的骨頭是？", opts: ["脊椎骨", "股骨", "肋骨", "肱骨"], ans: "股骨" },
    { q: "愛因斯坦著名的質能互換公式是？", opts: ["$F=ma$", "$E=mc^2$", "$V=IR$", "$a^2+b^2=c^2$"], ans: "$E=mc^2$" },
    { q: "哪種氣體是導致溫室效應的主要原因之一？", opts: ["氧氣", "氮氣", "二氧化碳", "氦氣"], ans: "二氧化碳" },
    { q: "地球自轉一圈大約需要多久？", opts: ["1小時", "12小時", "24小時", "365天"], ans: "24小時" },
    { q: "pH值等於7的溶液呈什麼性？", opts: ["酸性", "鹼性", "中性", "毒性"], ans: "中性" },
    { q: "光在真空中傳播的速度大約是每秒多少公里？", opts: ["30萬", "3萬", "3000", "300"], ans: "30萬" },
    { q: "台灣最高峰是哪一座山？", opts: ["玉山", "雪山", "南湖大山", "秀姑巒山"], ans: "玉山" },
    { q: "「Ilha Formosa」意指美麗之島，是哪國人對台灣的稱呼？", opts: ["荷蘭人", "葡萄牙人", "西班牙人", "英國人"], ans: "葡萄牙人" },
    { q: "二次大戰結束於哪一年？", opts: ["1918", "1937", "1945", "1950"], ans: "1945" },
    { q: "世界上面積最大的洲是？", opts: ["非洲", "亞洲", "歐洲", "北美洲"], ans: "亞洲" },
    { q: "中國歷史上唯一的一位女皇帝是？", opts: ["慈禧", "武則天", "呂雉", "韋后"], ans: "武則天" },
    { q: "日本的首都是哪個城市？", opts: ["大阪", "京都", "東京", "橫濱"], ans: "東京" },
    { q: "美國獨立宣言是在哪一年簽署的？", opts: ["1776", "1789", "1812", "1865"], ans: "1776" },
    { q: "下列哪一種動物不屬於哺乳類？", opts: ["鯨魚", "企鵝", "蝙蝠", "袋鼠"], ans: "企鵝" },
    { q: "太陽系中體積最大的行星是？", opts: ["地球", "火星", "木星", "土星"], ans: "木星" },
    { q: "下列哪一位科學家提出了「萬有引力」？", opts: ["牛頓", "愛因斯坦", "伽利略", "達爾文"], ans: "牛頓" },
    { q: "法國大革命爆發於哪一年？", opts: ["1789", "1812", "1848", "1914"], ans: "1789" },
    { q: "被稱為「文藝復興三傑」之一，並畫出《蒙娜麗莎》的是誰？", opts: ["達文西", "米開朗基羅", "拉斐爾", "畢卡索"], ans: "達文西" },
    { q: "清朝在台灣設置的第一個府治所在地是？", opts: ["台南", "台北", "台中", "高雄"], ans: "台南" },
    { q: "哪一位航海家被認為是第一個「發現」美洲新大陸的歐洲人？", opts: ["哥倫布", "麥哲倫", "達伽馬", "鄭和"], ans: "哥倫布" },
    { q: "台灣在歷史上曾被日本統治了多少年？", opts: ["30", "40", "50", "60"], ans: "50" },
    { q: "下列哪一個是古羅馬的代表性建築？", opts: ["競技場", "帕德嫩神廟", "獅身人面像", "萬里長城"], ans: "競技場" },
    { q: "「三國演義」中的「三國」是指哪三個國家？", opts: ["魏蜀吳", "齊楚燕", "秦趙魏", "隋唐宋"], ans: "魏蜀吳" },
    { q: "工業革命最早起源於哪一個國家？", opts: ["美國", "法國", "英國", "德國"], ans: "英國" },
    { q: "古埃及文明中最著名的地標是？", opts: ["金字塔", "艾菲爾鐵塔", "自由女神像", "比薩斜塔"], ans: "金字塔" }
  ]
};
